CC      = gcc
CFLAGS  = -Wall -g
TARGETS = Isaac_testFS

.PHONY: all clean

all: $(TARGETS)

Isaac_testFS: Isaac_libFS.o Isaac_testFS.o
	$(CC) $(CFLAGS) -o $@ $^

Isaac_libFS.o: Isaac_libFS.c Isaac_libFS.h
	$(CC) $(CFLAGS) -c $<

Isaac_testFS.o: Isaac_testFS.c Isaac_libFS.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f *.o $(TARGETS)
